---
title: "Codebuch"
output: html_document
author: "Miriam Hoffmann mh348"
---

## Codebuch

\*\*Codebuch\*\*\\

Bitte erstellen Sie ein \*\*two-mode Netzwerk\*\* (Mitgliedschaft in

Organisationen). Deshalb benötigen Sie das Node-Attribut type, da es um

Personen und Organisationen geht, codiert als 0 und 1.

\*Grundregeln\*: Keine Sonderzeichen, keine Leerzeichen, jede Beziehung in

maximal eine Zeile. IDs aus Edge- und Nodelist müssen identisch sein.

Folgende Variablen müssen erhoben werden:

\*\*Edgelist\*\*: \\

\- from (id), \\

\- to (id) \\

\- relationship \\

(1) Ministerium (auch angegliedert als Staatsekretär:in) \\

(2) politische Funktionen \\

(3) Ehrenamt \\

(4) Unternehmen und Aufsichtsräte \\

(5) Stipendien \\

(6) Berufstätigkeiten \\

(7) Studienort in In- und Ausland\\

\- year (Bezieht sich auf das Jahr, in dem die Variable relationship

erhoben wurde)

id als Initialen Vorname Nachname erfassen, also bei Franziska Brantner

z.B. "fb". Für Organisationen eine sinnvolle Abkürzung wählen.

\*\*Codebuch Relationship:\*\*\\

1 = Achtung: Regierung umfasst auch Staatsekretäre und das

Bundeskanzleramt, etc. hier sollte als Knoten das entsprechende

Ministerium angegeben werden.

2 = aktuelle und ehemalige politische Funktionen in politischen

Ausschüssen, Gremien und der Partei. etc. Das können auch frühere

Stationen gewesen sein, z.B. Geschäftsführer:in einer Partei, etc.

3 = umfasst alle Mitgliedschaften in NGOs, Stiftungen, Gedenkstätten,

etc: werden im Bundestagsprofil als Körperschaften öffentlichen Rechts

bezeichnet.

4 = Beteiligung an Unternehmen durch Mandate, etwa Aufsichtsratsmandate,

Gremien, etc.

5 = erhalten Stipendien (egal wann), etwa Deutsche Studienstiftung,

Parteinahe Stiftungen, Internationale Organisationen im In- und Ausland

etc.

6 = ausgeübte Berufstätigkeiten, falls vorhanden

7 = Studien- bzw. (längere) Aufenthaltsort(e) in In- und Ausland

\*\*Nodelist\*\* Kodierung entsprechend anpassen

\- id (identisch mit edgelist, aber hier nur einmalige Nennung),

\- name_short (Nachname)

\- name (voller Name)

\- type (0 = Person, 1 = Organisation/Ort/Verband etc.),

\- sex (Geschlecht 1= männlich 2=weiblich)

\- birth (Geburtsjahr)

\- position (1= Staatssekretär 2=Staatsminister 3=Bundesminister)

\- education (höchster Bildungsabschluss 1= Abitur 2= Bachelor 3= Master 4= Promotion 5= Diplom 6= Staatsexamen /=Master Articum)

\- subject (Fachrichtung bei Studium/Promotion 1 = Politikwissenschaften, 2 = Rechtswissenschaften, 3 = Wirtschaftswissenschaften, 4 = Sozialpädagogik)

\- party (Parteizugehörigkeit 1 = SPD, 2 = GRUENE, 3 = FDP)

\- religion (Religion 1 = evangelisch, 2 = römisch-katholisch, 3 = muslimisch)

\- kids (Anzahl der Kinder)

\- twitter (Anzahl follower)

\- instagram (Anzahl follower)

\- facebook (Anzahl follower)

\- youtube (Anzahl Abonnenten)

Fehlende Werte z.B. in der Nodelist leerlassen
